webtalk_init -webtalk_dir D:\\PD_sti_prj\\sti_prj_top\\STI_dac_v1.2\\STI_dac_v1.2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-12-26 17:14:45" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "rg605g5gnhqa1mjlofm6arsee7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_14" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12700H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "42.678 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1735195861924" -context "sdk\\\\application/1735195861924"
webtalk_add_data -client sdk -key hwid -value "1702694154852" -context "sdk\\\\application/1735195861924"
webtalk_add_data -client sdk -key bspid -value "1694576332000" -context "sdk\\\\application/1735195861924"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1735195861924"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1735195861924"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1735195861924"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1735195861924"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1735195861924"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1735195861924"
webtalk_add_data -client sdk -key projSize -value "432.69140625" -context "sdk\\\\application/1735195861924"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1735204485654"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1735204485654"
webtalk_add_data -client sdk -key BootgenCount -value "1" -context "sdk\\\\bsp/1735204485654"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1735204485654"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1735204485654"
webtalk_add_data -client sdk -key FlashCount -value "1" -context "sdk\\\\bsp/1735204485654"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1735204485654"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1735204485654"
webtalk_transmit -clientid 1916673792 -regid "" -xml D:\\PD_sti_prj\\sti_prj_top\\STI_dac_v1.2\\STI_dac_v1.2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\PD_sti_prj\\sti_prj_top\\STI_dac_v1.2\\STI_dac_v1.2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\PD_sti_prj\\sti_prj_top\\STI_dac_v1.2\\STI_dac_v1.2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
